- name: Checando atualizações do sistema
  apt:
    update_cache: true

- name: Habilitando configuração SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication yes'
  when: not (ansible_check_mode | bool)

- name: Reiniciando serviço SSH
  service:
    name: ssh
    state: restarted
  when: not (ansible_check_mode | bool)

- name: Baixando e executando repositório de instalação Docker
  shell: curl -fsSL '{{ repo_docker }}' | bash

- name: Iniciando serviço Docker
  service:
    name: docker
    state: started

- name: Mudando Hostname da instância
  ansible.builtin.hostname:
    name: LabCyberAcademy

- name: Criando um novo usuário para o laboratório
  user:
    name: '{{ config }}'
    password: '{{ pass }}'
    groups: docker
    state: present
    shell: /bin/bash
    create_home: yes
  when: not (ansible_check_mode | bool)

- name: Clonando repositório do Lab Cyber Academy
  git:
    repo: '{{ repo_github_app }}'
    dest: '{{ repo_app }}'
    clone: yes
    force: yes

- name: Movendo arquivo de configuração
  copy:
    src: '{{ repo_utils_connection }}'
    dest: '{{ repo_app }}'
  when: not (ansible_check_mode | bool)

- name: Movendo scripts dos Laboratórios
  copy:
    src: '{{ repo_utils_labs }}'
    dest: '{{ repo_labs }}'
    mode: '777'
  when: not (ansible_check_mode | bool)

- name: Clonando repositórios dos laboratórios
  git:
    repo: "{{ item.value }}"
    dest: "/opt/labs/{{ item.key | regex_replace('lab_', 'laboratory-') }}/cyber-range/"
    clone: yes
    force: yes
  loop: "{{ repos_github | dict2items }}"

- name: Instalando Open vSwitch
  apt:
    name: openvswitch-switch
    state: present

- name: Executando contêiner Docker com aplicação Lab Cyber Academy
  shell: cd '{{ repo_app }}' && docker compose up -d